language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install

script:
#  - php bin/console server:start
  #- php bin/console doctrine:database:create
  #- php bin/console doctrine:schema:create
  #- php bin/console doctrine:fixtures:load
  - ./vendor/bin/phpunit
