# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: $2y$12$yVNMPPg63zWgwosY8uqzYF0FM27HoxvTFHVwJSrPlJMAWWWzOW, roles: [ 'ROLE_USER', 'ROLE_API' ] }
                    admin: { password: $2y$12$UibGru0MT2wAJyBtWA12juBk4GrpovdeJrUd12hm4m5eczcoIuN3K, roles: [ 'ROLE_ADMIN', 'ROLE_API'] }

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main:
            #anonymous: ~
            # activate different ways to authenticate

        api:
            pattern:  ^/api
            anonymous: ~
            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        # require ROLE_ADMIN for /api
        - { path: ^/api, roles: ROLE_ADMIN }
